In [1]:
l = range(100000)

In [12]:
type(l)

range

In [2]:
%time for i in range(1,10): r = [x * 2 for x in l]

Wall time: 66.8 ms


In [13]:
type(r)

list

In [3]:
import numpy as np

In [4]:
a = np.arange(100000)

In [11]:
%time for i in range(1,10): a*2

Wall time: 998 µs


In [14]:
my_range = range(1,100000)

In [16]:
%time for i in range(10): my_list =  [x*2 for x in my_range]

Wall time: 65.8 ms


In [17]:
zeros = np.zeros((4,4))

In [18]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
ones_arrays = np.ones((5,5))

In [25]:
ones_arrays

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
empty_array = np.empty((7,7))

In [27]:
empty_array


array([[1.00954564e-311, 1.00954581e-311, 1.00954581e-311,
        1.00954583e-311, 1.00954586e-311, 1.00954587e-311,
        1.00954587e-311],
       [1.00954587e-311, 1.00954587e-311, 1.00954587e-311,
        1.00954587e-311, 1.00954587e-311, 1.00954587e-311,
        1.00954587e-311],
       [1.00954588e-311, 1.00954588e-311, 1.00954588e-311,
        1.00954588e-311, 1.00954588e-311, 1.00954588e-311,
        1.00954588e-311],
       [1.00954588e-311, 1.00954588e-311, 1.00954588e-311,
        1.00954588e-311, 1.00954588e-311, 1.00954588e-311,
        1.00954588e-311],
       [1.00954588e-311, 1.00954588e-311, 1.00954588e-311,
        1.00954588e-311, 1.00954588e-311, 1.00954588e-311,
        1.00954588e-311],
       [1.00954588e-311, 1.00954588e-311, 1.00954588e-311,
        1.00954588e-311, 1.00954588e-311, 1.00954581e-311,
        1.00954581e-311],
       [1.00954529e-311, 1.00954531e-311, 1.00954531e-311,
        1.00954531e-311, 1.00954531e-311, 1.00954531e-311,
        1.00954330

In [28]:
list_1 = [1,2,3,4,5]

In [29]:
array_1 =np.array(list_1)

In [30]:
array_1

array([1, 2, 3, 4, 5])

In [31]:
array_range = np.arange(1,20,5)

In [32]:
array_range

array([ 1,  6, 11, 16])

In [34]:
array_range.shape

(4,)

In [37]:
zeroes_1 = np.zeros((10,10))

In [38]:
zeroes_1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
zeroes_1.reshape((2,2,5,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [1]:
import numpy as np

In [2]:
empty_array = np.empty((3,3))

In [3]:
empty_array

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 6.76e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [4]:
empty_array.ndim

2

In [5]:
empty_array.dtype

dtype('float64')

In [6]:
a = np.arange(1,100,20)

In [7]:
a

array([ 1, 21, 41, 61, 81])

In [8]:
a.dtype

dtype('int32')

In [11]:
a = list(range(1,5))

In [12]:
a

[1, 2, 3, 4]

In [14]:
type(a)

list

In [15]:
a = range(1,5)

In [16]:
type(a)

range

In [17]:
a

range(1, 5)

In [18]:
empty_array.shape

(3, 3)

In [19]:
empty_array.dtype

dtype('float64')

In [20]:
empty_array.ndim

2

In [34]:
a = np.arange(2,21,2)

In [35]:
b = np.arange(22,41,2)

In [36]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [37]:
b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [38]:
a+b

array([24, 28, 32, 36, 40, 44, 48, 52, 56, 60])

In [39]:
c = a+b

In [40]:
c

array([24, 28, 32, 36, 40, 44, 48, 52, 56, 60])

In [41]:
a-b

array([-20, -20, -20, -20, -20, -20, -20, -20, -20, -20])

In [42]:
b-a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [43]:
a*2

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [44]:
b*3

array([ 66,  72,  78,  84,  90,  96, 102, 108, 114, 120])

In [45]:
b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [46]:
1/a

array([0.5       , 0.25      , 0.16666667, 0.125     , 0.1       ,
       0.08333333, 0.07142857, 0.0625    , 0.05555556, 0.05      ])

In [47]:
b/1

array([22., 24., 26., 28., 30., 32., 34., 36., 38., 40.])

In [48]:
1/b

array([0.04545455, 0.04166667, 0.03846154, 0.03571429, 0.03333333,
       0.03125   , 0.02941176, 0.02777778, 0.02631579, 0.025     ])

In [49]:
a*b

array([ 44,  96, 156, 224, 300, 384, 476, 576, 684, 800])

In [50]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [51]:
b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [52]:
a>6

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [53]:
a[a>6]

array([ 8, 10, 12, 14, 16, 18, 20])

In [54]:
b[b<20]

array([], dtype=int32)

In [55]:
b[b>30]

array([32, 34, 36, 38, 40])

In [56]:
b[b>=30]

array([30, 32, 34, 36, 38, 40])

In [57]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
a[5]

12

In [59]:
a[[1,3,5]]

array([ 4,  8, 12])

In [60]:
a<12

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [61]:
a[a<12]

array([ 2,  4,  6,  8, 10])

In [62]:
a[a<=12]

array([ 2,  4,  6,  8, 10, 12])

In [63]:
a[[5,6]]

array([12, 14])

In [65]:
a[a<12][[1,3]]

array([4, 8])

In [81]:
x = np.arange(1,101,1)

In [82]:
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [83]:
x.ndim

1

In [89]:
c = x.reshape((10,10))

In [90]:
c.ndim

2

In [105]:
c.shape

(10, 10)

In [91]:
c[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
c[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [98]:
c[0][4]

5

In [99]:
c[1:11:2]

array([[ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [106]:
c[1:11:2][0]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [104]:
c[1:11:2,0:5]

array([[11, 12, 13, 14, 15],
       [31, 32, 33, 34, 35],
       [51, 52, 53, 54, 55],
       [71, 72, 73, 74, 75],
       [91, 92, 93, 94, 95]])

In [107]:
c

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [111]:
c[::,0:1:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [112]:
c

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [121]:
c[0:11,0:11]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [122]:
c = np.arange(1,26).reshape(5,5)

In [123]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [136]:
c[::4,::4]

array([[ 1,  5],
       [21, 25]])

In [151]:
p = np.array([30,45,60])

###### p

In [152]:
p 

array([30, 45, 60])

In [153]:
np.sqrt(p)

array([5.47722558, 6.70820393, 7.74596669])

In [154]:
np.power(p,2)

array([ 900, 2025, 3600], dtype=int32)

In [155]:
q = np.array([75,90,105])

In [156]:
q

array([ 75,  90, 105])

In [158]:
np.add(p,q)

array([105, 135, 165])

In [159]:
np.amax(p)

60

In [161]:
np.cos(p)

array([ 0.15425145,  0.52532199, -0.95241298])

In [164]:
s =np.array([0,6,7,6777,8886,6776,455,74657,5462,2,254,2546,256,2523,245,24,2435,245])

In [165]:
np.where(s<200,"Not Ok","Ok")

array(['Not Ok', 'Not Ok', 'Not Ok', 'Ok', 'Ok', 'Ok', 'Ok', 'Ok', 'Ok',
       'Not Ok', 'Ok', 'Ok', 'Ok', 'Ok', 'Ok', 'Not Ok', 'Ok', 'Ok'],
      dtype='<U6')

In [169]:
s[s<200]

array([ 0,  6,  7,  2, 24])

In [170]:
s

array([    0,     6,     7,  6777,  8886,  6776,   455, 74657,  5462,
           2,   254,  2546,   256,  2523,   245,    24,  2435,   245])

In [171]:
k = np.array([2,3,4,0,9,76])

In [172]:
k.mean()

15.666666666666666

In [173]:
k.cumsum()

array([ 2,  5,  9,  9, 18, 94], dtype=int32)

In [174]:
k.cumprod()

array([ 2,  6, 24,  0,  0,  0], dtype=int32)

In [175]:
k>0

array([ True,  True,  True, False,  True,  True])

In [176]:
k.any()

True

In [177]:
k.all()

False

In [178]:
k[k>-1]

array([ 2,  3,  4,  0,  9, 76])

In [184]:
t = k>-1

In [185]:
k.any()

True

In [186]:
k.all

<function ndarray.all>

In [187]:
t.all()

True

In [188]:
t.any()

True

In [189]:
np.unique(k)

array([ 0,  2,  3,  4,  9, 76])

In [190]:
a = np.array([2,3,4,5,6])

In [191]:
b = np.array([2,3,77,5,6])

In [207]:
np.save('s',a)

In [208]:
s = np.load('s.npy')

In [209]:
s

array([2, 3, 4, 5, 6])

In [218]:
np.savez('s_p',f=a,g=b)

In [219]:
s_p=np.load('s_p.npz')

In [220]:
s_p

In [221]:
s_p['f']

array([2, 3, 4, 5, 6])

In [222]:
s_p['g']

array([ 2,  3, 77,  5,  6])

In [223]:
np.save('p',a)

In [224]:
a = np.load('p.npy')

In [225]:
a

array([2, 3, 4, 5, 6])

In [227]:
np.savez('q',a=a,b=b)

In [228]:
a_b = np.load('q.npz')

In [229]:
a_b['a']

array([2, 3, 4, 5, 6])

In [230]:
a_b['b']

array([ 2,  3, 77,  5,  6])

In [ ]:
!pip install jupyterthemes


In [1]:
a = [2,3,4,5]

In [ ]:
!pip uninstall jupyterthemes

In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4,5,6,7])

In [3]:
a.dtype

dtype('int32')

In [1]:
import numpy as np

In [2]:
a = np.arange(1,26).reshape(5,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
a[0:5:1,0:5:4]

array([[ 1,  5],
       [ 6, 10],
       [11, 15],
       [16, 20],
       [21, 25]])

In [1]:
import numpy as np

In [2]:
a = np.array([1,1,1,1])

In [3]:
b = np.diag(a)

In [4]:
b

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [17]:
b = np.diag(a,0)

In [18]:
b

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [19]:
a

array([1, 1, 1, 1])

In [20]:
b = np.array([2,3,4,5])

In [21]:
a.dot(b)

14

In [22]:
b.dot(a)

14

In [23]:
c = b.transpose()

In [24]:
c

array([2, 3, 4, 5])

In [25]:
a.dot(c)

14

In [26]:
a

array([1, 1, 1, 1])

In [28]:
g = np.diag(a).trace()

In [29]:
g

4

In [30]:
a = a.reshape(2,2)

In [31]:
a

array([[1, 1],
       [1, 1]])

In [33]:
b = np.linalg.det(a)

In [34]:
b

0.0

In [38]:
a = np.arange(1,5).reshape(2,2)

In [39]:
a

array([[1, 2],
       [3, 4]])

In [40]:
b = np.linalg.det(a)

In [41]:
b

-2.0000000000000004

In [42]:
round(b)

-2.0

In [44]:
a = np.arange(1,10).reshape(3,3)

In [45]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
b = np.linalg.det(a)

In [47]:
b

-9.51619735392994e-16

In [48]:
round(b)

-0.0

In [52]:
a = np.arange(2,6).reshape(2,2)

In [53]:
b = np.arange(6,10).reshape(2,2)

In [54]:
a

array([[2, 3],
       [4, 5]])

In [55]:
b

array([[6, 7],
       [8, 9]])

In [56]:
a+b

array([[ 8, 10],
       [12, 14]])

In [57]:
a*b

array([[12, 21],
       [32, 45]])

In [60]:
c=a.dot(b)

In [61]:
c

array([[36, 41],
       [64, 73]])

In [62]:
d = np.linalg.det(c)

In [63]:
d

3.999999999999999

In [64]:
round(d)

4.0

In [65]:
c

array([[36, 41],
       [64, 73]])

In [66]:
np.diag(c)

array([36, 73])

In [67]:
a = np.array([4,4,4,4])

In [68]:
b = np.diag(a)

In [69]:
b

array([[4, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 4]])

In [70]:
a = np.arange(2,6).reshape(2,2)

In [71]:
b = np.arange(6,10).reshape(2,2)

In [72]:
a

array([[2, 3],
       [4, 5]])

In [73]:
b

array([[6, 7],
       [8, 9]])

In [77]:
a = np.array([1,2,3,4])

In [79]:
a

array([1, 2, 3, 4])

In [85]:
b =a.reshape(2,2)

In [86]:
np.linalg.eig(b)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [99]:
b

array([[0, 0],
       [3, 4]])

In [105]:
c = b[1::,0:1:]=0

In [106]:
b

array([[0, 0],
       [0, 4]])

In [92]:
c

0

In [107]:
x =[[1,4,5,6,7,8,9,1,4],[11,14,15,16,17,18,19,11,14]]

In [109]:
d =np.array(x)

In [110]:
d

array([[ 1,  4,  5,  6,  7,  8,  9,  1,  4],
       [11, 14, 15, 16, 17, 18, 19, 11, 14]])

In [111]:
np.split(d,[4,6],axis = 1)

[array([[ 1,  4,  5,  6],
        [11, 14, 15, 16]]), array([[ 7,  8],
        [17, 18]]), array([[ 9,  1,  4],
        [19, 11, 14]])]